[[main]]
  identifier = "tienda"
  name = "Tienda Linux"
  url = "https://www.etsy.com/shop/LinuxFacil"
  weight = 1

[[main]]
  identifier = "twitch"
  name = "Twitch"
  url = "https://www.twitch.tv/linuxfacil"
  weight = 2

[[main]]
  identifier = "youtube"
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCkns-R5bBW3snQx7RAYRX-A"
  weight = 3

[[main]]
  identifier = "discord"
  name = "Discord"
  url = "https://discord.gg/7wtQA33pp5"
  weight = 4
